name: 🐛 Bug Report
description: Report a bug

body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: |
        Please describe the bug in as much detail as possible.

  - type: textarea
    id: reproduction
    validations:
      required: false
    attributes:
      label: Reproduction
      description: |
        Please link to a working reproduction that will help us verify and understand the bug.

  - type: input
    id: version
    validations:
      required: false
    attributes:
      label: Affected versions
      description: Please specify which version you are using.
